### ISSUE TITLE
Free disk space check appears too conservative

### ISSUE THREAD

**Issue by SimonPickup** [MobiusSync/MobiusSync#17]
Split from issue #1. Reported by @mstonermd:

> I sync a 30 GB folder without issues. Some minor file additions of now cause the following error. My iOS device has over 70 GB of free space on it still.

![Screenshot here: https://github.com/MobiusSync/MobiusSync/issues/1#issuecomment-748906263](https://user-images.githubusercontent.com/22255258/102768753-a7b3fc00-434f-11eb-8c11-53aa3019b00e.png)

### Initial Response

I suspect I know what is going on. Syncthing is probably technically acting correctly, however there are probably temporary files across the device that could be cleaned up by iOS to make enough space available. I think the iOS storage usage display includes temporary files under **free** space. I did notice this in my own testing but didn't investigate fully.

### Workaround

If my theory is correct, a workaround is to temporarily reduce the Syncthing Setting _Minimum Free Disk Space_. Even 1% is a lot of free space on modern devices. I am not sure this will trigger iOS to clean up temporary files, but it should keep you going.

We can do some tests at some point to confirm this, but I hope this helps in the short term.

### Fix

The fix needs to be in two parts:

1. Change the Syncthing free disk space check to use iOS native API to check free space net of temporary files.
2. Make sure Syncthing's use of low-level filesystem API actually triggers cleanup when required, and if not, work out a way to trigger it.

**Comment by mstonermd** [comment]
Yes, I changed it to 0.5% and now the error has resolved. Great idea, thanks

/MCS

**Comment by xiwenc** [comment]
Can you provide more detailed instructions? I lowered the "Minimum disk space" to 0.1, also tried 0.01, and 0.001 and even 0. But I'm still getting:

```
2023-07-12 10:35:37 Puller (folder "private" (XXXX), item "git/mx-cicd-templates/venv/lib/python3.11/site-packages/rsa-4.9.dist-info/WHEEL"): syncing: finishing: insufficient space in folder "private" (XXXX) (/private/var/mobile/Containers/Data/Application/2615CA87-829D-460F-B342-32CC13160B35/Documents/private): current 0.64 % < required 1 %
2023-07-12 10:35:37 "private" (XXXX): Failed to sync 18211 items
2023-07-12 10:35:37 Folder "private" (XXXX) isn't making sync progress - retrying in 1m49s.

```

> current 0.64 % < required 1 %

I see the setting persisted. Also tried force closing the app and rebooting my iPhone several times.

Somehow the setting is being ignored.

I purchased the premium version but I'm stuck with incomplete syncs

Please help

**Comment by msman0** [comment]
Hello, I'm also getting the error message. I have set the minimum at 1MB and the error message is the same. How can the error resolved? Thank you!

**Comment by artjomsR** [comment]
Also came here looking for a solution. I tried changing the % / Mb values in MobiusSync's settings. If anybody is still struggling with this, I didn't realise there's also an identical setting for each synced folder (Edit (folder) -> Advanced). I needed to change both values to proceed with my sync

**Comment by SimonPickup** [comment]
I have investigated this further and I am now confident that what Mobius is doing is technically correct. It is reacting based on the **actual** free space on the filesystem.

The unforrtunate thing is that the free space shown in Settings / General / About / Available is more optimistic. It is the **actual** free space on the filesystem **PLUS** temporary space which _could_ be freed by iOS when it purges temporary files and cache files. There is no way to trigger this clean-up.

We could change Mobius to use this more optimistic figure, but it would risk hard failures.

I think the current behaviour should stay and users can try the various heuristic methods documented elsewhere to force cleanup, or if you wish to live on the edge, disable Syncthing free space checks completely.

**Comment by mjraneri** [comment]
I disagree this is acceptable.  Users don’t have any way of forcing iOS to flush the cache to free up that space.   I think möbius should use the optimistic figure and let iOS flush the cache if it needs to free some of that space.  Isn’t that the way it’s supposed to work?  I have been struggling with this issue for a few weeks now.  It’s super frustrating that there’s no way to get past this error sometimes.

**Comment by SimonPickup** [comment]
I see your point. I figured that it would be even more frustrating for users to have data corruption.

I have researched if there is any way to force iOS to flush the cache but I have not found any way to do so.

I will at least reopen this issue so it is easier for people to find in future.

**Comment by mjraneri** [comment]
Is there a threshold where the OS will automatically trigger cache cleanup / garbage collection on its own?  Maybe you can impost two limits…. One limit is the one the user has selected which is tested against the optimistic free space figure and the other limit is a fixed value, (tested against the free space as currently calculated) say 50MB which is not configurable, high enough that there is some margin against out of memory errors and the corruption and hopefully also small enough that the OS will trigger cache cleanup on its own. 

Does this make sense?

**Comment by SimonPickup** [comment]
> Is there a threshold where the OS will automatically trigger cache cleanup / garbage collection on its own? Maybe you can impost two limits…. One limit is the one the user has selected which is tested against the optimistic free space figure and the other limit is a fixed value, (tested against the free space as currently calculated) say 50MB which is not configurable, high enough that there is some margin against out of memory errors and the corruption and hopefully also small enough that the OS will trigger cache cleanup on its own.
> 
> Does this make sense?

Definitely, but there is no way that is guaranteed to trigger cleanup. Without a guarantee there seems to always be a risk of data corruption.

I do have one idea that might help. More coming soon.

**Comment by 2600box** [comment]
Hello,

I ran into this problem when I started using Möbius Sync Pro, so I set the limit to 1%

Syncing stopped syncing some time ago and I just noticed now. So I set it to 0% and it works again.

I have 200GB+ free according the Settings.app readout.

Can you please confirm that this is expected behaviour and will not cause any problems?

Thank you

**Comment by shawnyeager** [comment]
I have over 150 GB free on disk, yet I'm seeing the same error. This is a bug, plain and simple. If it can't be resolved, the app is of no use.

**Comment by jaywalker0815** [comment]
I also agree that this should be addressed somehow.
For everyone else, I found a workaround (at least that worked for me):
I deleted an app with local files (in my case that was nextcloud since I now moved to syncthings). After deleting that app with all local data, I started möbius and it picked up space. Now it works with a 1.5% setting.

And fyi, changing the percentage settings without deleting an app didn’t do anything.

**Comment by jaywalker0815** [comment]
Another remark: Since there are plenty of apps out there being able to write gigabytes of data onto an iOS device, it should be possible to fix this, shouldn’t it? (Written from a non-dev standpoint)

**Comment by jaywalker0815** [comment]
Sorry for spamming this:
I added a few pictures, this increased the library size and I ran again in this error; despite having +100gb free on my iPhone.
If changing sizes of the library is such a big issue, could it be solved by reserving space for the library in the first place / when the app is being installed? Like a big but empty placeholder library?

**Comment by mjraneri** [comment]
There doesn’t need to be a large reservation of space in advance for a database.

this can seriously be handled with two thresholds. A small threshold which is a fixed value and is just concerned with making sure there is enough available space to avoid data corruption.  This should not be customizable but should be a small value like 100-200MB.

Then the threshold that can be set inside the UI can be the space available excluding the cache or uncollected garbage.

This way the app can lrotect against data corruption but can also allow syncthing to actually consume most of the remaining “free space” to actually trigger the garbage collection.

as it stands now if I have a 512GB phone and default 1% threshold, syncthing stops when I have 5GB free and iOS doesn’t see this as a low memory condition so it doesn’t trigger garbage collection/cache reclaim.

syncthing for iOS needs two thresholds.

**Comment by adiehl96** [comment]
Just adding that this bug is still persisting. I noticed something strange though. When I entered `iOS settings -> General -> About`, I noticed a low value for "Storage Available" (ca. 4,79 GB). However, on entering `iOS settings -> General -> iPhone Storage` I saw a much larger value indicated as available storage (ca. 117 GB). When I entered `iOS settings -> General -> About` again right away, I saw that the value had increased again to match the value from `iPhone Storage` and upon entering Moebius Sync, everything was syncing again. This made me wonder whether there exist two "local available storage" services in iOS, with one being used in combination with iCloud and one on a lower level, with the iCloud one being able to reserve space from the lower level one and thereby introducing this kind of bug, but who knows 🤷‍♀️

Device: iPhone 15 Pro Max
OS: iOS 18.1.1
Storage Capacity: 256 GB
Storage Available: ca. 117 GB

**Comment by Peed92** [comment]
I have the same Problems, nothing works. 
I tried everything Herr. 

syncing: finishing: insufficient space in folder "RetroArch" (...) (/private/var/mobile/Containers/Data/Application/.../Documents/RetroArch): current 0.66 % < required 1 %

iPhone 15 Pro

**Comment by esf2601** [comment]
In case anyone is still experiencing this issue. I wasn't able to resolve it using any of the steps. Luckily I was still early in the configuration of my folders so these steps weren't impactful. 

1. Delete the Mobius App
2. delete all the directories that have been synced to your iphone
3. Restart Iphone
4. reinstall/reconfigure using the .01 threshold

Not great, but after the reboot it looks like whatever cached data was removed, and i was able to proceed with the sync.
